services:
  nginx:
    networks:
      sigicnetwork:
      sigic-proxy:

  frontend-admin:
    image: sigic-frontend-admin:${COMPOSE_PROJECT_NAME}
    build:
      context: ./frontend
      dockerfile: ../overrides/frontend/Dockerfile
      args:
        NUXT_PUBLIC_APP_BASE_PATH: /admin/
    extra_hosts:
      - "${PLATFORM_HOST}:host-gateway"

  frontend-app:
    image: sigic-frontend-app:${COMPOSE_PROJECT_NAME}
    build:
      context: ./frontend
      dockerfile: ../overrides/frontend/Dockerfile
      args:
        NUXT_PUBLIC_APP_BASE_PATH: /app/
    extra_hosts:
      - "${PLATFORM_HOST}:host-gateway"

  django:
    extra_hosts:
      - "${PLATFORM_HOST}:host-gateway"

  celery:
    extra_hosts:
      - "${PLATFORM_HOST}:host-gateway"

  geoserver:
    extra_hosts:
      - "${PLATFORM_HOST}:host-gateway"

  keycloak:
    extra_hosts:
      - "${PLATFORM_HOST}:host-gateway"

  ia-engine:
    extra_hosts:
      - "${PLATFORM_HOST}:host-gateway"

  ia-queue:
    extra_hosts:
      - "${PLATFORM_HOST}:host-gateway"

  ia-lb:
    extra_hosts:
      - "${PLATFORM_HOST}:host-gateway"

  levantamiento:
    extra_hosts:
      - "${PLATFORM_HOST}:host-gateway"

networks:
  sigic-proxy:
    external: true
